name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
    steps:
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@v12
        working-directory: ${{github.workspace}}/cpp/build
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: ${{github.workspace}}/js
      - name: Build wasm
        working-directory: ${{github.workspace}}/cpp/build
        run: emcc -v
      - run: npm test
        working-directory: ${{github.workspace}}/js
