name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
    steps:
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@v12
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: ${{github.workspace}}/js
      - name: Build wasm
        working-directory: ${{github.workspace}}/cpp/build
        run: emcc -pthread ../src/FreqDbMetaData.cpp ../src/FreqDbReader.cpp ../src/ResultLeague.cpp ../src/LookupResult.cpp ../src/LookupHelpers.cpp -fwasm-exceptions -sASSERTIONS -s WASM=1 -s -I../include -o ../../js/freqDbReader.wasm.js --bind -s WASM_ASYNC_COMPILATION=0 -s EXIT_RUNTIME=1 -s PTHREAD_POOL_SIZE=8  -lnodefs.js
      - run: npm test
        working-directory: ${{github.workspace}}/js
